### ISSUE TITLE
Add fallback value for when value is not in valueMap

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/gnd-wikibase-converter#8]
As requested by @tbauer2811 

![image](https://user-images.githubusercontent.com/146040/184173482-c7e49e36-c771-486c-bed0-1d43bd0c04c2.png)

**Comment by JeroenDeDauw** [comment]
@tbauer2811 is this just for qualifiers, or for all valueMap? 

And can you confirm that the behavior should change from ignoring values not present in valueMap, to _always_ adding the fallback?

**Comment by tbauer2811** [comment]
@JeroenDeDauw yes I confirm. The fallback should work at least for qualifiers which have the valueMap setup.

**Comment by JeroenDeDauw** [comment]
@tbauer2811 imagine a statement with 3 qualifier mappings defined in the mapping

```json
"P1": {
	"field": "aaa",

	"subfield": "x",

	"qualifiers": {
		"P50": "a",
		"P51": {
			"subfield": "b",
			"valueMap": {
				"x": "Q40",
				"y": "Q41"
			},
		"P52": {
			"subfield": "c",
			"valueMap": {
				"z": "Q42",
				"zz": "Q43"
			}
		}
	}
}
```

Suppose these subfields are present in the PICA:
* `x` with value `whatever`
* `b` with value `wrong`
* `b` with value `wrong again`
* `c` with value `also wrong`
* `c` with value `z`

What should the resulting Wikibase Statement look like? Like this?

* Property 'P1'
* Value `whatever`
* Qualifiers:
    * `P52` = `Q42`
    * `P645` = `P51 = wrong`
    * `P645` = `P51 = wrong again`
    * `P645` = `P52 = also wrong`

Or does something else need to be stored in these strings for `P645`?

**Comment by tbauer2811** [comment]
@JeroenDeDauw this is absolute the right answer. This is how I was expecting.
No, there should nothing else being stored.
